### ISSUE TITLE
Graphql - How to query all regions in 'DG' (All german regions?)

### ISSUE THREAD

**Issue by P3nny** [datenguide/datenguide-api#1]
To be able to compare all regions in germany, I wold like to query all the regions in all federal states: 

{
  allRegions(page: 0, itemsPerPage: 10) {
    regions(parent: "DG", nuts:3) {
      id
      name
      BILABS(BILAG2: BILABS11, year: 2015, GES: [GESM, GESW, GESAMT]) {
        year
        BILAG2
        GES
        value
      }
    }
    page
    itemsPerPage
    total
  }
}

OUTPUT: 
{
  "data": {
    "allRegions": {
      "regions": [],
      "page": 0,
      "itemsPerPage": 10,
      "total": 0
    }
  }
}

Is my query wrong? Or is this a bug?

**Comment by simonwoerpel** [comment]
just without `parent`, this is the same query for all landkreise:

```
{
  allRegions(page: 0, itemsPerPage: 10) {
    regions(nuts: 3) {
      id
      name
      BILABS(BILAG2: BILABS11, year: 2015, GES: [GESM, GESW, GESAMT]) {
        year
        BILAG2
        GES
        value
      }
    }
    page
    itemsPerPage
    total
  }
}
```
