### ISSUE TITLE
Data in backend not up-to-date?

### ISSUE THREAD

**Issue by dpprdan** [datenguide/datenguide-api#107]
When running

```graphql
{
  region(id: "01001") {
    id
    name
    BEVSTD(statistics:R12411) {
      year
      value 
    }
  }
}
```

on https://api-next.datengui.de/graphql, I get 2015 as the latest year. On regionalstatistik.de data is available up until [2017](https://www.regionalstatistik.de/genesis/online/online?sequenz=tabelleErgebnis&selectionname=12411-01-01-4), however. 
The [same](https://tabular.genesapi.org/?data=12411:BEVSTD&time=2017&region=01001&labels=name) is true for tabular.genesapi.org. 

Is the data on GraqhQL API not up-to-date or am I missing something here? And if it is outdated, is there a regular update interval?

**Comment by sjockers** [comment]
Thanks for pointing this out. We have updated the data in the meantime so it should be up to date with regionalstatistik.de now.

> Is the data on GraqhQL API not up-to-date or am I missing something here? And if it is outdated, is there a regular update interval?

We have started to run nightly updates, so the data should generally be pretty recent. That being said, the API is currently in beta and things may be be out of date at times.

**Comment by dpprdan** [comment]
> We have updated the data in the meantime so it should be up to date with regionalstatistik.de now.

🤔 I don't see it yet.
![grafik](https://user-images.githubusercontent.com/1423562/68195309-ebff0400-ffb6-11e9-8151-8811479ae9a6.png)

FYI: The last example on https://docs.genesapi.org/12411/BEVSTD doesn't return any data.
![grafik](https://user-images.githubusercontent.com/1423562/68196174-7a27ba00-ffb8-11e9-8a71-ac04cad7efe4.png)

**Comment by crijke** [comment]
Sorry for the delay. We've just recently launched nightly updates and still needed to complete some updates to our infrastructure to make it work.

The data update did run in the meantime, can you check again if you see the complete data? The update also added data for region 'DG', so this should work now as well.

Thanks for reporting!

**Comment by dpprdan** [comment]
🚀 lookin' mighty fine 🚀 
Thanks!
