### ISSUE TITLE
Retrieve regions from elasticsearch instead of catalogue

### ISSUE THREAD

**Issue by crijke** [datenguide/datenguide-api#11]
currently regions are fetched from the destatis catalog and not from the actual data. should we fetch them from the actual data instead?

also see https://github.com/CorrelAid/datenguideR/issues/18

**Comment by dpprdan** [comment]
I think so: https://github.com/CorrelAid/datenguideR/issues/18 (or this is potentially related at least).

**Comment by crijke** [comment]
Until now datenguide-api has used a bundled list of regions, which got out of sync with the current statistics in the meantime. 

With the next release of datenguide-api (v0.2.0) we will load regions from the automatically updated names.json schema from data.genesapi.org to ensure region data is always up to date.

**Comment by dpprdan** [comment]
@crijke would it be okay/preferred to use names.json from data.genesapi.org in the R and Python packages re: https://github.com/CorrelAid/datenguideR/issues/18 (as opposed to querying the datenguide-api for this)?
