### ISSUE TITLE
Value attributes that are reused in multiple statistics have incorrect source information: WAHLSR, WAHL01 and others

### ISSUE THREAD

**Issue by crijke** [datenguide/datenguide-api#2]
Value attributes (like WAHL01) are sometimes reused in multiple statistics. This hasn't been taken into account in Datenguide yet and 'source' information was directly read from schema.json based on the field name only. WAHL01 for example, is used in both Europawahl and Bundestagswahl statistics, but we returned 'Bundeswahlstatistik' for both of these values.

```js
{
  region(id: "11") {
    id
    name
    WAHL01(year: 1994) {
      value
      source {
        name
        title_de
      }
    }
  }
}

```
'Source' is now determined based on the cube id (prefix of the cube id is the statistics id).

In addition, there is now a 'statistics' argument to let the user define which statistics should be returned (while still returning all of them, if the argument is not set).

Example: 

```js
{
  region(id: "11") {
    id
    name
    WAHL01(year: 1994, statistics: R14111) {
      value
      source {
        name
        title_de
      }
    }
  }
}
```
This query will only return WAHL01 from statistic 14111 (Bundestagswahl), but not Europawahl. 

- Added  the letter 'R' as prefix to the statistics id (for Regionalstatistik) as Ints ar not allowed by GraphQL syntax (has to begin with letter or underscore). Other ideas welcome..

**Comment by sjockers** [comment]
I think this is the most sensitive solution right now. Thanks so much for this! 

> Added the letter 'R' as prefix to the statistics id (for Regionalstatistik) as Ints ar not allowed by GraphQL syntax (has to begin with letter or underscore).

Using a Enum and prefixing with an 'R' makes sense. The Enum solution works great for autocompletion in GUIs.
